version: '3.8'

services:
  springboot-app:
    build: .
    image: springboot-app:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    deploy:
      mode: replicated
      replicas: 3  # Scale to 3 replicas