spring:
  application:
    name: SpringbootTemplate
  profiles:
    active: dev

server:
  port: 8080



# Database configuration for dev environment
#spring.datasource.url=jdbc:mysql://localhost:3306/dev_database
#spring.datasource.username=dev_user
#spring.datasource.password=dev_password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver  # Specify your database driver class

# Hibernate properties
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update